app:
  image: pmeier/cars_v2
  volumes:
    - client:/opt/app/client
    - common:/opt/app/common
    - server:/opt/app/server
  ports:
    - "80:80"
    - "3000:3000"
  environment:
    DEBUG: "socket.*"
  command: nodemon server.js